data_dir: data
environment_variables: {}
examples_filename: examples.yaml
description: Generate text from a prompt with this language model.
input_type: Any
model_class_filename: model.py
model_class_name: GPTJTransformerModel
model_framework: custom
model_metadata:
  avatar_url: https://cdn.baseten.co/production/static/explore/EleutherAI.png
  cover_image_url: https://cdn.baseten.co/production/static/explore/gpt-j.png
  tags:
  - text-generation
model_module_dir: model
model_name: Pygmalion-6b-Real
model_type: custom
python_version: py39
requirements:
  - torch
  - transformers
  - accelerate
resources:
  cpu: "3"
  memory: 14Gi
  use_gpu: true
  accelerator: A10G
secrets: {}
system_packages: []
spec_version: 2.0